export { default as BackArrow } from "./BackArrow";
export { default as Button } from "./Button";
export { default as ContentContainer } from "./ContentContainer";
export { default as ImgContainer } from "./ImgContainer";
export { default as InputTab } from "./InputTab";
export { default as Modal } from "./Modal";
// export { default as NabVar } from "./NabVar";
export { default as NextArrow } from "./NextArrow";
export { default as SubmitBtn } from "./SubmitBtn";
export { default as TextArea } from "./TextArea";
export { default as Title } from "./Title";
export { default as VersionBtn } from "./VersionBtn";
